main: su.nightexpress.economybridge.BridgePlugin
name: EconomyBridge
description: Unified library to handle currency plugins easy.
version: '${project.version}'
author: NightExpress
depend:
  - nightcore
load: STARTUP
api-version: 1.21
folia-supported: true